# Generated by Django 2.1 on 2018-08-27 08:05

from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [HStoreExtension()]
